<a href="https://colab.research.google.com/github/Shreya-07/CMPE258Assignment2/blob/main/CMPE258Assignment2TensorOperationsinPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR OPERATIONS IN PYTORCHt**

**Creating an empty Tensor**

In [2]:
import torch

In [3]:
x = torch.empty(2,3)
print(x)

tensor([[-1.8604e+06,  3.0617e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  3.0617e-41]])


**Creating tensors with random values**

In [4]:
x = torch.rand(2,3)
print(x)

tensor([[0.6199, 0.1085, 0.6299],
        [0.6018, 0.5806, 0.0661]])


**creating tensors with values as zeors or ones**

In [5]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [6]:
x = torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


**Creation of tensors for performing various operations**

In [7]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.0585, 0.0215],
        [0.5262, 0.5246]])
tensor([[0.8943, 0.5567],
        [0.4087, 0.7030]])


**summation of tensors**

In [8]:
z = x+y
print(z)

tensor([[0.9528, 0.5783],
        [0.9349, 1.2276]])


**subtraction of tensors**

In [9]:
z = torch.sub(x,y)
print(z)

tensor([[-0.8358, -0.5352],
        [ 0.1175, -0.1784]])


**Multiplication of tensors**

In [10]:
z = torch.mul(x,y)
print(z)

tensor([[0.0523, 0.0120],
        [0.2150, 0.3688]])


**Division of tensors**

In [11]:
z = torch.div(x,y)
print(z)

tensor([[0.0654, 0.0387],
        [1.2874, 0.7463]])


**Slicing Operation**

In [12]:
x = torch.rand(5,3)
print(x)
print(x[:,1])
print(x[1,:])
print(x[1,1])
print(x[1,1].item())

tensor([[0.9898, 0.5107, 0.1683],
        [0.5134, 0.3599, 0.5960],
        [0.0383, 0.5340, 0.8466],
        [0.5366, 0.4085, 0.2253],
        [0.4953, 0.5239, 0.0198]])
tensor([0.5107, 0.3599, 0.5340, 0.4085, 0.5239])
tensor([0.5134, 0.3599, 0.5960])
tensor(0.3599)
0.3598911762237549


**Reshaping a tensor**

In [13]:
x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)

tensor([[0.4620, 0.7660, 0.5909, 0.5304],
        [0.4990, 0.1300, 0.5260, 0.9382],
        [0.7761, 0.4222, 0.9340, 0.2603],
        [0.0477, 0.4991, 0.3106, 0.0470]])
tensor([0.4620, 0.7660, 0.5909, 0.5304, 0.4990, 0.1300, 0.5260, 0.9382, 0.7761,
        0.4222, 0.9340, 0.2603, 0.0477, 0.4991, 0.3106, 0.0470])
