<a href="https://colab.research.google.com/github/Shreya-07/CMPE258Assignment2/blob/main/CMPE258Assignment2EINSUM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**EINSUM**

In [1]:
import torch

In [2]:
X = torch.rand((2,3))

In [3]:
#Permutaation of Tensors
torch.einsum("ij->ji",X)

tensor([[0.9048, 0.4566],
        [0.5145, 0.2110],
        [0.5723, 0.4314]])

In [4]:
#summation
torch.einsum("ij->",X)

tensor(3.0906)

In [5]:
#column sum
torch.einsum("ij->j",X)

tensor([1.3613, 0.7255, 1.0038])

In [6]:
#row sum
torch.einsum("ij->i",X)

tensor([1.9916, 1.0990])

In [7]:
#Matrix-Vector Multiplication
v = torch.rand((1,3))
torch.einsum("ij, kj->ik", X, v)

tensor([[1.0330],
        [0.5951]])

In [8]:
#Matrix Matrix Multiplication
torch.einsum("ij, kj->ik", X, X)

tensor([[1.4109, 0.7686],
        [0.7686, 0.4391]])

In [9]:
#Dot Product
torch.einsum("i, i->", X[0], X[0])

tensor(1.4109)

In [10]:
#Dot product with Matrix
torch.einsum("ij, ij->", X, X)

tensor(1.8500)

In [11]:
#Hadamard Product (element-wise multiplication)
torch.einsum("ij, ij->ij", X, X)

tensor([[0.8186, 0.2647, 0.3276],
        [0.2085, 0.0445, 0.1861]])

In [12]:
#outer product
a = torch.rand((3))
b = torch.rand((5))
torch.einsum("i, j->ij", a, b)

tensor([[0.2094, 0.7763, 0.6017, 0.1908, 0.7521],
        [0.0377, 0.1397, 0.1083, 0.0343, 0.1354],
        [0.0235, 0.0871, 0.0675, 0.0214, 0.0844]])

In [13]:
#Batch Matrix Multiplication
a = torch.rand((3, 2, 5))
b = torch.rand((3, 5, 3))
torch.einsum("ijk, ikl->ijl", a, b)

tensor([[[2.2562, 2.1845, 0.6661],
         [1.3852, 1.3782, 0.5111]],

        [[1.1636, 0.9135, 1.5548],
         [0.7460, 1.0311, 0.6056]],

        [[1.2949, 1.3523, 1.0572],
         [0.8837, 1.0219, 0.8265]]])

In [14]:
#Matrix Diagonal
X = torch.rand((3, 3))
torch.einsum("ii->i", X)

tensor([0.2290, 0.4548, 0.4786])

In [15]:
#Matrix Trace
torch.einsum("ii->", X)

tensor(1.1624)